### ISSUE TITLE
Page 444 not in greyscale

### ISSUE THREAD

**Issue by yusufabukar** [sufone/qawl#36]
Don't know if this is an issue but page 444 (Yā Sīn) is in colour and the others are not!

**Comment by mr-islam** [comment]
Hi, as salamu alaykum, thank you for reporting this issue and sorry for my late reply! (Worked on some other Qawl features and got busy with other stuff 😅)

I have just confirmed this bug... This is not intended, and is probably a mistake from the source Quran mushaf images 

This problem can be corrected manually for the source image using an image editor... But I don't think I have the time to do that for such a small bug.

If you like, you are most welcome to upload an edited version of the image:

Or, I'll just wait for a future chance to implement even higher quality mushaf images that will of course fix this too, insha Allah

**Comment by mr-islam** [comment]
Hope you are doing well dear brother!

I just published an update that includes this fix, and of course mentioned it in the newsletter: https://buttondown.email/naved/archive/arabic-sentence-construction-qawlapp-updates/

**Comment by yusufabukar** [comment]
Cool! I've updated Qawl on my computer now 😄
