### ISSUE TITLE
Bug: Cannot go back after selecting links in "settings" on Mac

### ISSUE THREAD

**Issue by mBilG** [sufone/qawl#56]
Once you click on the github link in the settings, there is no way to go back.
Need to close and re-open the app.

**Comment by mr-islam** [comment]
As salamu alaykum, 

This sounds very similar to an issue from the Linux #19… something to do with the Electron / Browser method being used to open external links.

I'll take a look at this soon, thank you for reporting! ❤

**Comment by mr-islam** [comment]
I have just fixed this in the latest commit, it was a silly mistake by me!

Thank you again so much for letting me know, this was a big problem ❤️

**Comment by mr-islam** [comment]
This is now in the latest `v0.0.7` release!
